[package]
name = "film_taggy"
license = "GPL-3,0-or-later"
version = "0.1.0"
authors = ["Zouroboros <zouroboros@zoho.eu>"]
edition = "2021"

[dependencies]

[dependencies.gtk]
version = "0.15.5"

[dependencies.glib]
version = "0.15.11"

[dependencies.rexiv2]
version = "0.9.1"
